### ISSUE TITLE
running esp32+bg96 with aws iot 

### ISSUE THREAD

**Issue by nices0325** [codezoo-ltd/CodeZoo_CATM1_Arduino#2]
Is there any recommanded aws iot cloud connection with esp32+bg96 library??

It's hard for me to connect aws iot cloud because AWS doesn't give any library with arduino.. Thanks

**Comment by codezoo-ltd** [comment]
It is recommended to use a service that implements ppp with esp32-idf. 
There are some good examples on github.com. 

Good Luck!!!
